export const actionTypes = {
  FILTER_PARAMETER: "FILTER_PARAMETER",
  SEARCH_PARAMETER: "SEARCH_PARAMETER",
  GET_PRODUCTS: "GET_PRODUCTS",
  SET_LOADİNG: "SET_LOADİNG",
  SET_ERROR: "SET_ERROR",
};
